train:
    arch: ???
    scheduler: cosine
    lr_anneal_cycles: 1
    smooth_cross_entropy: false
    batch_size: 96 
    learning_rate: 0.025
    learning_rate_min: 0.0
    momentum: 0.9
    weight_decay: 0.0003
    init_channels: 36
    layers: 20
    autoaugment: false
    cutout: true
    cutout_length: 16
    auxiliary: true
    auxiliary_weight: 0.4
    drop_path_prob: 0.2
    grad_clip: 5


